### ISSUE TITLE
Foursquare key doesn't work anymore

### ISSUE THREAD

**Issue by helenhe329** [dartmouth-cs98/17f-plan-it-server#15]
{"response":{},"meta":{"requestId":"5a6a26a6dd579773a212cf72","errorType":"not_authorized","errorDetail":"Consumer disabled.","code":403}}

**Comment by helenhe329** [comment]
I think that it might be the date that we provide to the URL in the controller

**Comment by helenhe329** [comment]
https://developer.foursquare.com/docs/api/troubleshooting/errors

**Comment by helenhe329** [comment]
Maybe we do have to do user auth :( 

https://developer.foursquare.com/docs/api/configuration/authentication

**Comment by helenhe329** [comment]
https://github.com/DanToml/Bees/blob/master/lib/bees/client.ex

**Comment by jiyunsung** [comment]
fixed!
